In [ ]:
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/MyDrive/Project/HUPTrafficdata

/content/drive/MyDrive/Project/HUPTrafficdata


In [ ]:
!ls

go  left  leftlane  right  stop  X.pkl	y.pkl


In [ ]:
DIRECTORY = ''

CATEGORIES = ['right','left','stop','go']

In [ ]:
import os
data = []

for category in CATEGORIES:
    path = os.path.join(DIRECTORY, category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        label = CATEGORIES.index(category)
        arr = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        new_arr = cv2.resize(arr, (60, 60))
        data.append([new_arr, label])

In [ ]:
data

[[array([[254, 254, 254, ..., 254, 254, 254],
         [254, 254, 254, ..., 254, 254, 254],
         [254, 254, 254, ..., 254, 254, 254],
         ...,
         [ 20,  20,  20, ...,  20,  20,  20],
         [ 20,  20, 226, ..., 137,  20,  20],
         [ 20,  20,  20, ...,  20,  20,  20]], dtype=uint8),
  1],
 [array([[255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         ...,
         [ 90, 210, 175, ...,  91,  90,  92],
         [ 88, 228, 195, ..., 159, 164,  92],
         [ 95, 134,  90, ...,  92,  87,  93]], dtype=uint8),
  1],
 [array([[  0,   0,   0, ...,   0,   0,   0],
         [  0,   0, 255, ..., 255,   0,   0],
         [  0, 255, 255, ..., 255, 255,   0],
         ...,
         [  0, 255, 255, ..., 255, 255,   0],
         [  0,   0, 255, ..., 255,   0,   0],
         [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8),
  1],
 [array([[245, 247, 254, ..., 254, 252, 246],
         [254, 244, 2

In [ ]:
data[0][1]

1

In [ ]:
import random

random.shuffle(data)

In [ ]:
X = []
y = []

In [ ]:
for features, label in data:
    X.append(features)
    y.append(label)

In [ ]:
X = np.array(X)
y = np.array(y)

In [ ]:
X

array([[[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 254, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [ 90, 210, 175, ...,  91,  90,  92],
        [ 88, 228, 195, ..., 159, 164,  92],
        [ 95, 134,  90, ...,  92,  87,  93]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0, 255, ..., 255,   0,   0],
        [  0, 255, 255, ..., 255, 255,   0],
        ...,
        [  0, 255, 255, ..., 255, 255,   0],
        [  0,   0, 255, ..., 255,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]],

       ...,

       [[110, 110, 110, ..., 208, 207, 206],
        [110, 110, 110, ..., 207, 206, 204],
        [109, 108, 110, ..., 206, 207, 205

In [ ]:
y

array([3, 1, 1, 3, 3, 1, 3, 3, 1, 1])

In [ ]:
import pickle

In [ ]:
pickle.dump(X, open('X.pkl', 'wb'))
pickle.dump(y, open('y.pkl', 'wb'))

In [ ]:

X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [ ]:
X

array([[[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 254, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [ 90, 210, 175, ...,  91,  90,  92],
        [ 88, 228, 195, ..., 159, 164,  92],
        [ 95, 134,  90, ...,  92,  87,  93]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0, 255, ..., 255,   0,   0],
        [  0, 255, 255, ..., 255, 255,   0],
        ...,
        [  0, 255, 255, ..., 255, 255,   0],
        [  0,   0, 255, ..., 255,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]],

       ...,

       [[110, 110, 110, ..., 208, 207, 206],
        [110, 110, 110, ..., 207, 206, 204],
        [109, 108, 110, ..., 206, 207, 205

In [ ]:
y

array([3, 1, 1, 3, 3, 1, 3, 3, 1, 1])

In [ ]:
X = X/255
X

X = X.reshape(-1, 60, 60, 1)


In [ ]:

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten


In [ ]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(4, activation = 'softmax'))

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X, y, epochs=50, validation_split=0.1)

Epoch 1/50
1/1 [==============================] - 2s 2s/step - loss: 1.4642 - accuracy: 0.0000e+00 - val_loss: 1.1078 - val_accuracy: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 141ms/step - loss: 0.9210 - accuracy: 0.5556 - val_loss: 0.8114 - val_accuracy: 0.0000e+00
Epoch 3/50
1/1 [==============================] - 0s 131ms/step - loss: 0.6328 - accuracy: 0.6667 - val_loss: 0.4800 - val_accuracy: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 114ms/step - loss: 0.4937 - accuracy: 1.0000 - val_loss: 0.5221 - val_accuracy: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 110ms/step - loss: 0.4013 - accuracy: 0.8889 - val_loss: 0.1582 - val_accuracy: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 123ms/step - loss: 0.3484 - accuracy: 1.0000 - val_loss: 0.3479 - val_accuracy: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 114ms/step - loss: 0.2895 - accuracy: 0.8889 - val_loss: 0.1228 - val_accuracy: 1.0000
Epoch 8/50


In [ ]:
import cv2
import keras

In [ ]:
import numpy as np
CATEGORIES = ['right','left','stop','go']


def image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    new_arr = cv2.resize(img, (60, 60))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 60, 60, 1)
    return new_arr



In [ ]:
prediction = model.predict([image('/content/drive/MyDrive/Project/HUPTrafficdata/right/r6.jpg')])
print(CATEGORIES[prediction.argmax()])
print(prediction)

1/1 [==============================] - 0s 136ms/step
go
[[0. 0. 0. 1.]]
